### ISSUE TITLE
c5ac035 breaks build on clang-3.4

### ISSUE THREAD

**Issue by klmr** [Valloric/ycmd#791]
Running `./install.py` on macOS 10.10.5 with clang-3.4 (clang 3.4.2 fails with the following error message:

> <code>FAILED: /usr/local/bin/clang++-3.4  -stdlib=libc++  -DUSE_CLANG_COMPLETER -DYCMD_CORE_VERSION=28 -Dycm_core_EXPORTS -I/Users/rudolph/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm -I/Users/rudolph/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/ClangCompleter -isystem /Users/rudolph/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/BoostParts -isystem /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7 -isystem ycm/../clang+llvm-4.0.0-x86_64-apple-darwin/include -nostdinc++ -isystem /usr/local/lib/llvm-3.4/include/c++/v1 -stdlib=libc++ -fcolor-diagnostics -O3 -DNDEBUG -fPIC   -std=c++11 -MD -MT ycm/CMakeFiles/ycm_core.dir/IdentifierUtils.cpp.o -MF ycm/CMakeFiles/ycm_core.dir/IdentifierUtils.cpp.o.d -o ycm/CMakeFiles/ycm_core.dir/IdentifierUtils.cpp.o -c /Users/rudolph/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/IdentifierUtils.cpp</code>

> …

> <code>/Users/rudolph/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/IdentifierUtils.cpp:120:12: error: chosen constructor is explicit in copy-initialization  </code>
    <code>return {};</code>

As far as I can see, this is an actual bug, introduced in c5ac03521cfb0834b6a9c59c15fd27fb8bee35d4: the [`std::map` copy constructor in C++11 is `explicit`](https://stackoverflow.com/q/45029992/1968), initialisation by `{}` in a `return` statement is thus forbidden (though g++ erroneously accepts the code).

A simple fix would be to replace the line with

```c++
return FiletypeIdentifierMap{};
```

**Comment by bstaletic** [comment]
How exactly have you invoked `./install.py`? 

> A simple fix would be to replace the line with
return FiletypeIdentifierMap{};

Have you tried this? If you're sure it would work make a PR. I know OS X bot has never complained about that line and we are supposed to support clang-3.3 and up. So if there is a problem it should be fixed.

**Comment by Valloric** [comment]
This looks like a real bug to me. I thought our Travis test matrix included a build with Clang, but [that does not appear to be the case.](https://github.com/Valloric/ycmd/blob/master/.travis.yml#L13-L14) If we just add "clang" to the compiler list, this would double our test matrix which we don't want, so this will need a bit more nuance.

[Travis docs talk about this a bit.](https://docs.travis-ci.com/user/languages/c/) Should be possible for us to add just one extra row to our matrix that uses clang.
