### PR TITLE
[READY] Fix compilation with Clang 3.4

### LINKED ISSUE #791: c5ac035 breaks build on clang-3.4
Running `./install.py` on macOS 10.10.5 with clang-3.4 (clang 3.4.2 fails with the following error message:

> <code>FAILED: /usr/local/bin/clang++-3.4  -stdlib=libc++  -DUSE_CLANG_COMPLETER -DYCMD_CORE_VERSION=28 -Dycm_core_EXPORTS -I/Users/rudolph/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm -I/Users/rudolph/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/ClangCompleter -isystem /Users/rudolph/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/BoostParts -isystem /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7 -isystem ycm/../clang+llvm-4.0.0-x86_64-apple-darwin/include -nostdinc++ -isystem /usr/local/lib/llvm-3.4/include/c++/v1 -stdlib=libc++ -fcolor-diagnostics -O3 -DNDEBUG -fPIC   -std=c++11 -MD -MT ycm/CMakeFiles/ycm_core.dir/IdentifierUtils.cpp.o -MF ycm/CMakeFiles/ycm_core.dir/IdentifierUtils.cpp.o.d -o ycm/CMakeFiles/ycm_core.dir/IdentifierUtils.cpp.o -c /Users/rudolph/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/IdentifierUtils.cpp</code>

> …

> <code>/Users/rudolph/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/IdentifierUtils.cpp:120:12: error: chosen constructor is explicit in copy-initialization  </code>
    <code>return {};</code>

As far as I can see, this is an actual bug, introduced in c5ac03521cfb0834b6a9c59c15fd27fb8bee35d4: the [`std::map` copy constructor in C++11 is `explicit`](https://stackoverflow.com/q/45029992/1968), initialisation by `{}` in a `return` statement is thus forbidden (though g++ erroneously accepts the code).

A simple fix would be to replace the line with

```c++
return FiletypeIdentifierMap{};
```

### PR DESCRIPTION
**Pull request by micbou**
Compiling with Clang 3.4 results in the following error:
```
cpp/ycm/IdentifierUtils.cpp:120:12: error: chosen constructor is explicit in copy-initialization
    return {};
           ^~
/usr/include/c++/v1/map:838:14: note: constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
1 error generated.
```
See issue https://github.com/Valloric/ycmd/issues/791.

As Valloric suggested, this PR adds a Linux build with Clang 3.4 on Travis. We are supposed to support Clang 3.3 but 3.4 is the oldest version available on Travis.

I'll update the PR with the fix once the Clang build failed.

Fixes #791.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/793)

### CODE REVIEW

**Comment by micbou** [comment]
Updated by reverting the change in commit https://github.com/Valloric/ycmd/commit/c5ac03521cfb0834b6a9c59c15fd27fb8bee35d4 that introduced the Clang compilation error.

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/793#-:-Kp67HOyiI2hfoB0Z10j:b-n5bb7o)*

**Comment by Valloric** [comment]
Sweet!

:lgtm:

Thanks for the PR!

**Comment by bstaletic** [comment]
I thought osx on travis would be using clang by default.
:lgtm: 
@zzbot r=Valloric

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/793#-:-KpLdBjWRyL2I_Pw5qrR:b-anxqbu)*

**Comment by micbou** [comment]
> I thought osx on travis would be using clang by default.

That's the case but, AFAIK, it's a modified version of Clang, more recent than 3.4 (at least 3.9).

@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/793#-:-KpLrLoz5Q3IZ_QJARra:b-e4gq92)*
